### ISSUE TITLE
Seems like OPUS is not included

### ISSUE THREAD

**Issue by egorsmkv** [kyutai-labs/sphn#1]
Cargo.toml [has](https://github.com/LaurentMazare/sphn/blob/main/Cargo.toml#L18C1-L18C10) `all` feature flag as it is described in the symphonia's github project to include all formats and codecs but in my test OPUS codec is not complied 

You can look at maturin's log here:

https://colab.research.google.com/drive/1kBvFIutNTA6XRQUItHB8iceHg6ram64v?usp=sharing

Any suggestions?

**Comment by LaurentMazare** [comment]
I think opus in symphonia might be a work in progress and not available yet, e.g. see [this](https://github.com/pdeljanov/Symphonia/tree/4f41954de75e2447753f3e522cc7345ec414a703/symphonia-codec-opus), so not much to suggest here I'm afraid :(

**Comment by egorsmkv** [comment]
Ahhh, I see

Thanks!
